### ISSUE TITLE
Add ability to assign keyboard shortcuts for each color

### ISSUE THREAD

**Issue by irvinm** [irvinm/TST-Colorize-Tabs#3]

**Comment by tdlf32** [comment]
Hello, thank you for this great Fork. I read the discussion in the "disscussion" tab, it would be interesting to integrate a shortcut for each color, it's a great idea and could save us a lot of time!

**Comment by Mike6547** [comment]
Has this feature already been integrated?

**Comment by irvinm** [comment]
Try the latest build, I've finished with the initial implementation.
